@startuml
entity "ユーザー" as User {
  *id : int <<PK>>
  ---
  名称 : string
  email : string
}

entity "場所" as Location {
  *id : int <<PK>>
  ---
  *ユーザーid : int <<FK>>
  名称 : string
}

entity "場所詳細" as LocationDetail {
  *id : int <<PK>>
  ---
  *場所id : int <<FK>>
  タイトル : string
  画像パス : string
  説明 : string
}

User ||--o{ Location : owns
Location ||--o{ LocationDetail : contains
@enduml
